<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\SummerSchool.DataAccess\SummerSchool.DataAccess.csproj" />
    <ProjectReference Include="..\..\Core\SummerSchool.Entity\SummerSchool.Entity.csproj" />
  </ItemGroup>

</Project>
